# Generated by Django 4.0.3 on 2022-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('password', models.TextField(null='empty')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('subject', models.CharField(max_length=200, null='empty')),
                ('message', models.CharField(max_length=300, null='empty')),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('password', models.TextField(null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('gender', models.CharField(max_length=200, null='empty')),
                ('aadharnumber', models.CharField(max_length=200, null='empty')),
                ('rationcardnumber', models.TextField()),
            ],
        ),
    ]
