# Generated by Django 4.0.3 on 2022-04-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_user',
            new_name='Contact',
        ),
    ]
