# Generated by Django 4.0.3 on 2022-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('price', models.CharField(max_length=20, null='empty')),
                ('stock', models.CharField(max_length=20, null='empty')),
                ('discription', models.CharField(max_length=300, null='empty')),
            ],
        ),
    ]
