# Generated by Django 4.0.3 on 2022-04-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
