# Generated by Django 4.0.3 on 2022-04-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0005_rename_stock_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_tb',
        ),
    ]
