# Generated by Django 4.0.3 on 2022-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0007_rename_contact_contact_tb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration_tb',
            name='verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='rationcardnumber',
            field=models.CharField(max_length=200, null='empty'),
        ),
    ]
