# Generated by Django 4.0.3 on 2022-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0008_user_registration_tb_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtype', models.CharField(max_length=30, null='empty')),
                ('date', models.CharField(max_length=20, null='empty')),
                ('message', models.CharField(max_length=20, null='empty')),
                ('read', models.BooleanField(default='False')),
            ],
        ),
    ]
