# Generated by Django 4.0.3 on 2022-04-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0009_notification_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe_tb',
            new_name='Subscribers_tb',
        ),
    ]
