# Generated by Django 4.0.3 on 2022-04-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_ration_app', '0011_product_tb_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcount', models.CharField(max_length=10)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_ration_app.product_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_ration_app.user_registration_tb')),
            ],
        ),
    ]
