from django.urls import path
from digital_ration_app import views

urlpatterns = [
    path('',views.indexpage),
    path('index/',views.indexpage),
    path('login/',views.loginuser),
    path('adminlogin/',views.adminlogin),
    path('adminlogout/',views.adminlogout),
    path('userlogout/',views.userlogout),
    path('userregistration/',views.userregistration),
    path('userlist/',views.userlist),
    path('events/',views.eventpage),
    path('about/',views.aboutpage),
    path('products/',views.productpage),
    path('services/',views.servicespage),
    path('mail/',views.mailpage),
    path('household/',views.householdpage),
    path('vegetables/',views.vegetablespage),
    path('kitchen/',views.kitchenpage),
    path('subscribe/',views.subscribe),
    path('single/',views.singleproduct),
    path('productlist/',views.productlist),
    path('addproduct/',views.addproduct),
    path('userlist/',views.userlist),
    path('verifieduserlist/',views.verifieduserlist),
    path('nonverifieduserlist/',views.nonverifieduserlist),
    path('editproduct/',views.editproduct),
    path('checkout/',views.checkout),
    path('userverification/',views.userverification),
    path('issuecard/',views.issuecard),
    path('changepassword/',views.changepassword),
    path('notifications/',views.notifications),
    path('subscribers/',views.subscribers),
    path('notificationdelete/',views.notificationdelete),
    path('purchasedproduct/',views.purchasedproduct),
    path('profileview/',views.profileview),
    path('january/',views.january),
    path('february/',views.february),
    path('march/',views.march),
    path('april/',views.april),
    path('may/',views.may),
    path('june/',views.june),
    path('july/',views.july),
    path('august/',views.august),
    path('september/',views.september),
    path('october/',views.october),
    path('november/',views.november),
    path('december/',views.december),
    path('addtokart/',views.addtokart),
    # path('kartview/',views.kartview),
    path('removeitem/',views.removeitem),
    path('edititem/',views.edititem),
    path('updatecount/',views.updatecount),
    path('feedback/',views.feedback),
    path('purchasehistory/',views.purchasehistory),
    

    ]